### ISSUE TITLE
Exception when adding "Carousel" content element

### ISSUE THREAD

**Issue by crydotsnake** [neos/Neos.Demo#114]
Hello Neos Friends 😊  👋🏼  !

## Description
In the current Neos version, you get an exception when you want to add the content element. There was already a ticket for this: #77 but I thought it would be better to open a new ticket.

![Bildschirmfoto 2021-09-19 um 14 27 51](https://user-images.githubusercontent.com/39345336/133927708-9e8bab07-4fb2-4fda-8b3d-ed168482cd9f.png)

## Informations
- Neos Version: `"neos/neos": "~7.1.0",`
- Neos.Demo Package Version: `"neos/demo": "^7.1",`
- Development Environment: DDEV

**Comment by crydotsnake** [comment]
I have the assumption that Neos does not pull the latest state from the `Neos.Demo` package. Because the directory structure in the Git repository is different than in my project. I have installed the `Neos.Demo` Package normally with Neos.

For example the `Configuration` folder in the root folder is different.

## My Project:
![Bildschirmfoto 2021-09-19 um 15 32 10](https://user-images.githubusercontent.com/39345336/133929461-8dd0b17d-fed3-42f3-827d-4548b6320f7d.png)

## Git Repository
![Bildschirmfoto 2021-09-19 um 15 33 12](https://user-images.githubusercontent.com/39345336/133929482-6fd4fa92-9f12-4c8a-9f69-272a2b606798.png)

If I am correct, then this ticket is unnecessary here i think, since it would not be a bug at this point.

**Comment by Sebobo** [comment]
The fix is there, but there was no upmerge and release since then.

**Comment by bwaidelich** [comment]
has this been fixed in the meantime?

**Comment by jonnitto** [comment]
Fixed with #137
