### ISSUE TITLE
New Demo for Neos 8.3

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.Demo#147]
## Ideas from Neos Sprint Hamburg 2022

- [x] Presentation folder with all components inside
  - [x] More complex components like columns will have a subfolder to contain their parts
  - [x] Remove atoms, section and block folders
- [x] Document Mixin in Page mergen
- [x] Remove restrictions and enforce adding constraints on all nodetypes @Sebobo 
- [x] Rename CKConfig 
- [ ] Add readme to subfolders to explain their use
- [x] MenuItems Recursion @jonnitto 
- [x] Remove context dependent setting and replace with simple setting access set by context
- [x] Rename Splide to Slider
- [ ] Release notes should contain information about pruning and reimporting the new content
- [ ] Explain that Tailwind is an example and people could use anything
- [x] Chapters still have to be renamed @jonnitto 

## v9 new CR specifics

- [x] Create separate issue #156

**Comment by Sebobo** [comment]
@jonnitto here are the todos for the demo we discussed

**Comment by jonnitto** [comment]
I think MenuItems Recursion is no longer needed with [#3911](https://github.com/neos/neos-development-collection/pull/3911)

**Comment by Sebobo** [comment]
@jonnitto constraints are in. Only the chapter should have its own collection with custom restrictions but makes sense to do that when it's refactored to `Article`

**Comment by Sebobo** [comment]
We removed the book and added the blog
