### ISSUE TITLE
TASK: Remove usage of Neos.Neos:PrimaryContent to render the main content collection

### ISSUE THREAD

**Issue by ahaeslich** [neos/Neos.Demo#170]
Triggered by testing the pull request https://github.com/neos/neos-development-collection/pull/4281#issuecomment-1549938033 I would suggest to switch the usage of `Neos.Neos:PrimaryContent` to `Neos.Neos:ContentCollection` as I can see no advantage of using it in the demo.

Any objections? If not: Do we want to target the changes for v8.3 or introduce them in the v9 branch?

Current usages:
- Page.fusion
- Blog.fusion
- BlogPosting.fusion
- LandingPage.fusion

**Comment by ahaeslich** [comment]
@jonnitto / @Sebobo / @mficzel any thoughts?

**Comment by mficzel** [comment]
Never really figured out what primary content is anyways. So fine with me. I suggest to target 9.0

**Comment by Sebobo** [comment]
With the initial page concept it had some uses for extensibility. Like I used it for my blog package which didn't have its own page type back then. But I think nowadays there is no use for it anymore.

I'm fine with replacing it even in 8.3 now. We will have to use 8.3 for quite a while now as example.
