### ISSUE TITLE
TASK: Fix empty reference default value

### ISSUE THREAD

**Issue by mhsdesign** [neos/Neos.Demo#173]
https://github.com/neos/Neos.Demo/blob/82ee8967a0937df88dffcaeb2b4cfd42d0f1c134/NodeTypes/Content/BlogPostingList/BlogPostingList.yaml#L28

https://neos-project.slack.com/archives/C3MCBK6S2/p1688542914136669?thread_ts=1688542588.698759&cid=C3MCBK6S2

![image (1)](https://github.com/neos/Neos.Demo/assets/85400359/20154f7a-ded1-44bd-bad3-5be568916ccb)

**Comment by crydotsnake** [comment]
Does this even need the `defaultValue:` property?
