### ISSUE TITLE
Two YouTube content elements

### ISSUE THREAD

**Issue by crydotsnake** [neos/Neos.Demo#180]
Currently, we have two content elements for displaying a youtube video on the page.

1. `Neos.Demo:Content.CarouselYouTube`
2. `Neos.Demo:Content.YouTube`

Is there a specific reason for that? If not, we should decide which one of the elements should be removed.

**Comment by mhsdesign** [comment]
1 is probably specifically for inside sliders? But anyway there should be restrictions only allow allowing one at a time
