### ISSUE TITLE
Exception when adding "Content" content element

### ISSUE THREAD

**Issue by crydotsnake** [neos/Neos.Demo#77]
![Bildschirmfoto 2020-04-06 um 16 01 30](https://user-images.githubusercontent.com/39345336/78566688-e6387380-781f-11ea-84e8-a918aca4b2b8.png)

**Comment by Sebobo** [comment]
We have an invalid node type in https://github.com/neos/Neos.Demo/blob/master/Configuration/NodeTypes.Content.Carousel.yaml#L26

This one should be removed or correctly cleaned up.

**Comment by jan-harmsen** [comment]
confirmed, same bug shows up in a fresh Neos Demo installation.
Required change (without knowing the internals of Neos) seems to be: `Neos.Demo/Configuration/NodeTypes.Content.Carousel.yaml` line 26:

from `'Neos.Demo:Content.Carousel.Collection':` to `'Neos.Demo:Collection.Content.Carousel':`

**Comment by crydotsnake** [comment]
Hello!

In the newest Neos Version i get the same error again

![Bildschirmfoto 2021-09-19 um 14 27 51](https://user-images.githubusercontent.com/39345336/133927555-8a8cff2b-a9e2-46fa-9b49-25eb4c1be37e.png)
