### ISSUE TITLE
PHP Warning for every hit on the 404 page

### ISSUE THREAD

**Issue by paavo** [neos/Neos.Demo#81]
**Neos throws a PHP Warning for every hit on the 404 page.** 

```
Neos\Flow\Mvc\Controller\Exception\InvalidControllerException
No controller could be resolved which would match your request. Package key: "", controller name: "Standard". (GET http://domain.tld/non-existing-url)
```

`"/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Dispatcher.php in Neos\\Flow\\Mvc\\Dispatcher_Original::resolveController"`
```
throw new Controller\Exception\InvalidControllerException($exceptionMessage, 1303209195, null, $request);
```

Im not sure if this is a problem of the Neos.Demo or the Neos Core.

**Comment by Sebobo** [comment]
@paavo is this solved now for you?
At least I don't get warnings.

**Comment by paavo** [comment]
Looks like this is solved 😅
